# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\GitHub\pulse_power\pyside_program\test.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(541, 510)
        self.window_signal = QtWidgets.QGroupBox(Form)
        self.window_signal.setGeometry(QtCore.QRect(10, 10, 241, 221))
        self.window_signal.setFlat(False)
        self.window_signal.setCheckable(False)
        self.window_signal.setObjectName("window_signal")
        self.label_signal_duration = QtWidgets.QLabel(self.window_signal)
        self.label_signal_duration.setGeometry(QtCore.QRect(10, 70, 161, 20))
        self.label_signal_duration.setObjectName("label_signal_duration")
        self.label_repetition_rate = QtWidgets.QLabel(self.window_signal)
        self.label_repetition_rate.setGeometry(QtCore.QRect(10, 120, 211, 20))
        self.label_repetition_rate.setTextFormat(QtCore.Qt.AutoText)
        self.label_repetition_rate.setObjectName("label_repetition_rate")
        self.label_rezim = QtWidgets.QLabel(self.window_signal)
        self.label_rezim.setGeometry(QtCore.QRect(10, 20, 181, 16))
        self.label_rezim.setObjectName("label_rezim")
        self.rezim = QtWidgets.QComboBox(self.window_signal)
        self.rezim.setGeometry(QtCore.QRect(10, 40, 191, 22))
        self.rezim.setObjectName("rezim")
        self.signal_duration = QtWidgets.QLCDNumber(self.window_signal)
        self.signal_duration.setGeometry(QtCore.QRect(10, 90, 51, 21))
        self.signal_duration.setMidLineWidth(0)
        self.signal_duration.setSmallDecimalPoint(False)
        self.signal_duration.setObjectName("signal_duration")
        self.repetition_rate = QtWidgets.QLCDNumber(self.window_signal)
        self.repetition_rate.setGeometry(QtCore.QRect(10, 140, 51, 21))
        self.repetition_rate.setMidLineWidth(0)
        self.repetition_rate.setSmallDecimalPoint(False)
        self.repetition_rate.setObjectName("repetition_rate")
        self.window_vattmeter = QtWidgets.QGroupBox(Form)
        self.window_vattmeter.setGeometry(QtCore.QRect(270, 240, 171, 61))
        self.window_vattmeter.setObjectName("window_vattmeter")
        self.vattmeter = QtWidgets.QLineEdit(self.window_vattmeter)
        self.vattmeter.setGeometry(QtCore.QRect(20, 20, 141, 21))
        self.vattmeter.setObjectName("vattmeter")
        self.window_trakt = QtWidgets.QGroupBox(Form)
        self.window_trakt.setGeometry(QtCore.QRect(10, 240, 241, 121))
        self.window_trakt.setObjectName("window_trakt")
        self.Dp = QtWidgets.QLineEdit(self.window_trakt)
        self.Dp.setGeometry(QtCore.QRect(10, 40, 211, 20))
        self.Dp.setObjectName("Dp")
        self.label_Dp = QtWidgets.QLabel(self.window_trakt)
        self.label_Dp.setGeometry(QtCore.QRect(10, 20, 211, 20))
        self.label_Dp.setObjectName("label_Dp")
        self.label_kosl = QtWidgets.QLabel(self.window_trakt)
        self.label_kosl.setGeometry(QtCore.QRect(10, 70, 231, 20))
        self.label_kosl.setObjectName("label_kosl")
        self.kosl = QtWidgets.QLCDNumber(self.window_trakt)
        self.kosl.setGeometry(QtCore.QRect(10, 90, 51, 21))
        self.kosl.setMidLineWidth(0)
        self.kosl.setSmallDecimalPoint(False)
        self.kosl.setObjectName("kosl")
        self.window_otvet = QtWidgets.QGroupBox(Form)
        self.window_otvet.setGeometry(QtCore.QRect(20, 380, 221, 111))
        self.window_otvet.setObjectName("window_otvet")
        self.pulse_power = QtWidgets.QLCDNumber(self.window_otvet)
        self.pulse_power.setGeometry(QtCore.QRect(10, 20, 71, 41))
        self.pulse_power.setMidLineWidth(0)
        self.pulse_power.setSmallDecimalPoint(False)
        self.pulse_power.setObjectName("pulse_power")
        self.pm = QtWidgets.QLabel(self.window_otvet)
        self.pm.setGeometry(QtCore.QRect(90, 40, 16, 16))
        self.pm.setObjectName("pm")
        self.range_pulse_power = QtWidgets.QLCDNumber(self.window_otvet)
        self.range_pulse_power.setGeometry(QtCore.QRect(110, 30, 61, 31))
        self.range_pulse_power.setMidLineWidth(0)
        self.range_pulse_power.setSmallDecimalPoint(False)
        self.range_pulse_power.setObjectName("range_pulse_power")
        self.Rasschet = QtWidgets.QPushButton(self.window_otvet)
        self.Rasschet.setGeometry(QtCore.QRect(10, 70, 51, 31))
        self.Rasschet.setObjectName("Rasschet")
        self.Clear = QtWidgets.QPushButton(self.window_otvet)
        self.Clear.setGeometry(QtCore.QRect(70, 70, 61, 31))
        self.Clear.setObjectName("Clear")
        self.Metodichka = QtWidgets.QPushButton(self.window_otvet)
        self.Metodichka.setGeometry(QtCore.QRect(140, 70, 71, 31))
        self.Metodichka.setObjectName("Metodichka")
        self.window_dialog = QtWidgets.QGroupBox(Form)
        self.window_dialog.setGeometry(QtCore.QRect(270, 310, 261, 181))
        self.window_dialog.setObjectName("window_dialog")
        self.dialog = QtWidgets.QTextBrowser(self.window_dialog)
        self.dialog.setGeometry(QtCore.QRect(10, 20, 241, 151))
        self.dialog.setObjectName("dialog")
        self.window_element = QtWidgets.QGroupBox(Form)
        self.window_element.setGeometry(QtCore.QRect(270, 10, 261, 221))
        self.window_element.setObjectName("window_element")
        self.label_element = QtWidgets.QLabel(self.window_element)
        self.label_element.setGeometry(QtCore.QRect(10, 20, 161, 16))
        self.label_element.setObjectName("label_element")
        self.element = QtWidgets.QComboBox(self.window_element)
        self.element.setGeometry(QtCore.QRect(10, 40, 171, 22))
        self.element.setObjectName("element")
        self.label_ke = QtWidgets.QLabel(self.window_element)
        self.label_ke.setGeometry(QtCore.QRect(10, 70, 181, 20))
        self.label_ke.setObjectName("label_ke")
        self.ke = QtWidgets.QLCDNumber(self.window_element)
        self.ke.setGeometry(QtCore.QRect(10, 90, 51, 21))
        self.ke.setMidLineWidth(0)
        self.ke.setSmallDecimalPoint(False)
        self.ke.setObjectName("ke")
        self.label_Gpr = QtWidgets.QLabel(self.window_element)
        self.label_Gpr.setGeometry(QtCore.QRect(10, 120, 221, 20))
        self.label_Gpr.setTextFormat(QtCore.Qt.AutoText)
        self.label_Gpr.setObjectName("label_Gpr")
        self.Gpr = QtWidgets.QLCDNumber(self.window_element)
        self.Gpr.setGeometry(QtCore.QRect(10, 140, 51, 21))
        self.Gpr.setMidLineWidth(0)
        self.Gpr.setSmallDecimalPoint(False)
        self.Gpr.setObjectName("Gpr")
        self.label_koks = QtWidgets.QLabel(self.window_element)
        self.label_koks.setGeometry(QtCore.QRect(10, 170, 251, 20))
        self.label_koks.setTextFormat(QtCore.Qt.AutoText)
        self.label_koks.setObjectName("label_koks")
        self.koks_2 = QtWidgets.QLCDNumber(self.window_element)
        self.koks_2.setGeometry(QtCore.QRect(10, 190, 51, 21))
        self.koks_2.setMidLineWidth(0)
        self.koks_2.setSmallDecimalPoint(False)
        self.koks_2.setObjectName("koks_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Dialog"))
        self.window_signal.setTitle(_translate("Form", "1. Сигнал на выходе станции"))
        self.label_signal_duration.setText(_translate("Form", "Длительность сигнала - t, мкс"))
        self.label_repetition_rate.setText(_translate("Form", "Частота повторения импульсов - Fи, Гц"))
        self.label_rezim.setText(_translate("Form", "Выберете режим работы станции:"))
        self.window_vattmeter.setTitle(_translate("Form", "4. Показания ваттметра Px, Вт"))
        self.window_trakt.setTitle(_translate("Form", "3. Тракт"))
        self.label_Dp.setText(_translate("Form", "Суммарное ослабление тракта - Dp, Дб"))
        self.label_kosl.setText(_translate("Form", "Коэффециент ослабления тракта - kосл, раз"))
        self.window_otvet.setTitle(_translate("Form", "Импульсная мощность Pимп, кВт"))
        self.pm.setText(_translate("Form", "±"))
        self.Rasschet.setText(_translate("Form", "Расчёт"))
        self.Clear.setText(_translate("Form", "Очистить"))
        self.Metodichka.setText(_translate("Form", "Методичка"))
        self.window_dialog.setTitle(_translate("Form", "Окно диалога"))
        self.window_element.setTitle(_translate("Form", "2. Элемент перехода"))
        self.label_element.setText(_translate("Form", "Выберете элемент перехода:"))
        self.label_ke.setText(_translate("Form", "Коэффециент эффективности - Кэ"))
        self.label_Gpr.setText(_translate("Form", "Модуль коэффециента отражения - |Гпр|"))
        self.label_koks.setText(_translate("Form", "Коэффециент исп. коасксиального перехода - а"))



